server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdata;MODE=PostgreSQL
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog-test.xml
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8